---
- name: deploy linux vm
  hosts: localhost
  become: false

  tasks:
    - name:  Clone a virtual machine from Linux template and customize
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter }}"
        state: present
        validate_certs: no 
        folder: Test
        template: "{{ template }}"
        name: "{{ vm_name }}"
        cluster: LNK-LAB
        networks:
          - name: "{{ vlan_id }}"
            type: static
            ip: "{{ ip_address }}"
            netmask: 255.255.255.0
            gateway: "{{ gateway_address }}"
            start_connected: yes
        wait_for_ip_address: true
        customization:
          hostname: " {{ vm_name }}""
          domain: "{{ guest_domain }}"
          dns_servers:
            - "{{ dns_1 }}"
            - "{{ dns_2 }}"
          dns_suffix:
            - stnvdi.local
          script_text: |
            #!/bin/bash
            touch /tmp/touch-from-playbook
      delegate_to: localhost
