---
- name: vcenter info
  hosts: localhost
  become: false

  tasks:
    - name: Login into vCenter and get cookies
      uri:
        url: https://{{ vcenter_hostname }}/rest/com/vmware/cis/session
          force_basic_auth: yes
          validate_certs: no
          method: POST
          user: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          register: vcsa_session

    - name: Set session ID as fact
        set_fact:
          vcsa_session_id: "{{ vcsa_session.json.value }}"   
        
    - name: Gather vmware host facts from vCenter
      community.vmware.vmware_host_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
      register: host_facts
      delegate_to: localhost

    - name: The output of Product, Version, Build, Update info for ESXi
      debug:
        msg:
          - "Output : {{ host_facts }}"
