---
- name: vcenter info
  hosts: localhost
  become: false

  tasks:
    - name: Gather vmware host facts from vCenter
      community.vmware.vmware_host_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
      register: host_facts
      delegate_to: localhost

    - name: The output of Product, Version, Build, Update info for ESXi
      debug:
        msg:
          - "Output" : {{ host_facts }}
