---
- name: vcenter maintenance mode
  hosts: localhost
  become: false

  tasks:
    - name: Enter VSAN-Compliant Maintenance Mode
      community.vmware.vmware_maintenancemode:
        hostname: nevcenter-lab.ne.gov
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ esxi_hostname }}"
#        vsan: ensureObjectAccessibility
        evacuate: true
        validate_certs: no 
        timeout: 3600
        state: present
      delegate_to: localhost
