---
- name: vcenter maintenance mode
  hosts: all
  become: false

  tasks:
    - name: Enter VSAN-Compliant Maintenance Mode
      community.vmware.vmware_maintenancemode:
        hostname: nevcenter-lab.stone.ne.gov
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: nevhlabls1b02.ne.gov
        vsan: ensureObjectAccessibility
        evacuate: true
        timeout: 3600
        state: present
#    delegate_to: localhost
