---
- name: vcenter datastore info
  hosts: all
  become: false

  tasks:
    - name: Export facts from datastore
      community.vmware.vmware_datastore_info:
        hostname: "{{ hostname }}"
        username: '{{ username }}'
        password: "{{ password }}"
        datacenter: "{{ datacenter }}"
        validate_certs: no
      delegate_to: localhost
      register: datastore_facts
